main: game.cpp resource_manager.cpp texture.cpp shader.cpp sprite_renderer.cpp
	g++ program.cpp  game.cpp sprite_renderer.cpp resource_manager.cpp texture.cpp shader.cpp -std=c++11 -o a.out -lGLEW -lglfw3 -lGL -lX11 -lXi -lXrandr -lXxf86vm -lXinerama -lXcursor -lrt -lm -pthread -ldl -lSOIL -lassimp
clean:
	rm main.exec
