# Linux
main: main.cpp Shader.h Camera.h
	g++ main.cpp -std=c++11 -o a.out -lGLEW -lglfw3 -lGL -lX11 -lXi -lXrandr -lXxf86vm -lXinerama -lXcursor -lrt -lm -pthread -ldl -lassimp
clean:
	rm main.exec
# MACOS
# main: main.cpp Shader.h Camera.h
# 	g++ main.cpp -std=c++11 -o a.out -lGLEW -lglfw3 
# clean:
# 	rm main.exec