# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.6.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.6.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/wth/Desktop/Shoot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/wth/Desktop/Shoot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.6.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.6.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wth/Desktop/Shoot/CMakeFiles /Users/wth/Desktop/Shoot/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wth/Desktop/Shoot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Shoot

# Build rule for target.
Shoot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Shoot
.PHONY : Shoot

# fast build rule for target.
Shoot/fast:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/build
.PHONY : Shoot/fast

box.o: box.cpp.o

.PHONY : box.o

# target to build an object file
box.cpp.o:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/box.cpp.o
.PHONY : box.cpp.o

box.i: box.cpp.i

.PHONY : box.i

# target to preprocess a source file
box.cpp.i:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/box.cpp.i
.PHONY : box.cpp.i

box.s: box.cpp.s

.PHONY : box.s

# target to generate assembly for a file
box.cpp.s:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/box.cpp.s
.PHONY : box.cpp.s

box_renderer.o: box_renderer.cpp.o

.PHONY : box_renderer.o

# target to build an object file
box_renderer.cpp.o:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/box_renderer.cpp.o
.PHONY : box_renderer.cpp.o

box_renderer.i: box_renderer.cpp.i

.PHONY : box_renderer.i

# target to preprocess a source file
box_renderer.cpp.i:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/box_renderer.cpp.i
.PHONY : box_renderer.cpp.i

box_renderer.s: box_renderer.cpp.s

.PHONY : box_renderer.s

# target to generate assembly for a file
box_renderer.cpp.s:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/box_renderer.cpp.s
.PHONY : box_renderer.cpp.s

game.o: game.cpp.o

.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i

.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s

.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/game.cpp.s
.PHONY : game.cpp.s

gameBodyBase.o: gameBodyBase.cpp.o

.PHONY : gameBodyBase.o

# target to build an object file
gameBodyBase.cpp.o:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/gameBodyBase.cpp.o
.PHONY : gameBodyBase.cpp.o

gameBodyBase.i: gameBodyBase.cpp.i

.PHONY : gameBodyBase.i

# target to preprocess a source file
gameBodyBase.cpp.i:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/gameBodyBase.cpp.i
.PHONY : gameBodyBase.cpp.i

gameBodyBase.s: gameBodyBase.cpp.s

.PHONY : gameBodyBase.s

# target to generate assembly for a file
gameBodyBase.cpp.s:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/gameBodyBase.cpp.s
.PHONY : gameBodyBase.cpp.s

program.o: program.cpp.o

.PHONY : program.o

# target to build an object file
program.cpp.o:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/program.cpp.o
.PHONY : program.cpp.o

program.i: program.cpp.i

.PHONY : program.i

# target to preprocess a source file
program.cpp.i:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/program.cpp.i
.PHONY : program.cpp.i

program.s: program.cpp.s

.PHONY : program.s

# target to generate assembly for a file
program.cpp.s:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/program.cpp.s
.PHONY : program.cpp.s

resource_manager.o: resource_manager.cpp.o

.PHONY : resource_manager.o

# target to build an object file
resource_manager.cpp.o:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/resource_manager.cpp.o
.PHONY : resource_manager.cpp.o

resource_manager.i: resource_manager.cpp.i

.PHONY : resource_manager.i

# target to preprocess a source file
resource_manager.cpp.i:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/resource_manager.cpp.i
.PHONY : resource_manager.cpp.i

resource_manager.s: resource_manager.cpp.s

.PHONY : resource_manager.s

# target to generate assembly for a file
resource_manager.cpp.s:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/resource_manager.cpp.s
.PHONY : resource_manager.cpp.s

shader.o: shader.cpp.o

.PHONY : shader.o

# target to build an object file
shader.cpp.o:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/shader.cpp.o
.PHONY : shader.cpp.o

shader.i: shader.cpp.i

.PHONY : shader.i

# target to preprocess a source file
shader.cpp.i:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/shader.cpp.i
.PHONY : shader.cpp.i

shader.s: shader.cpp.s

.PHONY : shader.s

# target to generate assembly for a file
shader.cpp.s:
	$(MAKE) -f CMakeFiles/Shoot.dir/build.make CMakeFiles/Shoot.dir/shader.cpp.s
.PHONY : shader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Shoot"
	@echo "... box.o"
	@echo "... box.i"
	@echo "... box.s"
	@echo "... box_renderer.o"
	@echo "... box_renderer.i"
	@echo "... box_renderer.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... gameBodyBase.o"
	@echo "... gameBodyBase.i"
	@echo "... gameBodyBase.s"
	@echo "... program.o"
	@echo "... program.i"
	@echo "... program.s"
	@echo "... resource_manager.o"
	@echo "... resource_manager.i"
	@echo "... resource_manager.s"
	@echo "... shader.o"
	@echo "... shader.i"
	@echo "... shader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

